name: githubby
dependencies:
  github: any
  polymer: ^1.0.0-rc.11
  web_components: ^0.12.0
  browser: ^0.10.0
  source_gen: ^0.4.0
dev_dependencies:
  test: ^0.12.0
transformers:
- polymer:
    entry_points:
    - web/index.html
