name: githubby
dependencies:
  github:
    git:
      url: https://github.com/johnpryan/github.dart.git
      ref: add-pr-list-state
  polymer: ^1.0.0-rc.11
  web_components: ^0.12.0
  browser: ^0.10.0
  source_gen: ^0.4.0
  polymer_time_ago: any
  args: any
  intl: any
dev_dependencies:
  test: ^0.12.0
dependency_overrides:
  reflectable: ^0.5.0
transformers:
- polymer:
    entry_points:
    - web/index.html
